vcs:
  uri: https://github.com/alpha-hack-program/doc-bot-kotaemon.git
  ref: main
  name: alpha-hack-program/doc-bot-kotaemon
  dir: src

createNamespace: true

pythonVersion: 3.9-ubi8

# gitPatSecret: git-pat-bc-secret

gitSslVerify: true
modelDeploymentUploadTektonPipelineName: fraud-detection-kfp-upload
sourceWorkspaceSize: 2Gi

genericWebhookSecretKey: 'ABCDEFGHIJKL'
githubWebhookSecretKey: 'ABCDEFGHIJKL'

dataScienceProjectDisplayName: kotaemon
dataScienceProjectNamespace: kotaemon

openaiApiKey: 'ABCDEFGHI'
azureOpenaiApiKey: 'ABCDEFGHI'
cohereApiKey: 'ABCDEFGHI'
graphragApiKey: 'ABCDEFGHI'
pdfServicesClientSecret: 'ABCDEFGHIJKL'
milvusToken: 'ABCDEFGHIJKL'
milvusPassword: 'ABCDEFGHIJKL'
oracleUsername: 'ABCDEFGHIJKL'
oraclePassword: 'ABCDEFGHIJKL'
oracleDsn: 'ABCDEFGHIJKL'
oracleTableName: 'ABCDEFGHIJKL'
oracleDistanceStrategy: 'euclidean'

openaiApiBase: https://mistral-7b-predictor-doc-bot.apps.cluster-8q7tj.8q7tj.sandbox277.opentlc.com/v1
openaiChatModel: /mnt/models/
openaiEmbeddingsModel: text-embedding-ada-002
azureOpenaiEndpoint: ''
openaiApiVersion: 2024-02-15-preview
azureOpenaiChatDeployment: gpt-35-turbo
azureOpenaiEmbeddingsDeployment: text-embedding-ada-002
localModel: llama3.1:8b
localModelEmbeddings: nomic-embed-text
graphragLlmModel: gpt-4o-mini
graphragEmbeddingModel: text-embedding-3-small
azureDiEndpoint: ''
azureDiCredential: ''
pdfServicesClientId: ''
milvusHost: http://vectordb-milvus.milvus.svc.cluster.local
milvusPort: 19530
milvusCollectionsFile: llamacollection

