# This file contains the secrets that are used by the kotaemon application
kind: Secret
apiVersion: v1
metadata:
  name: kotaemon-secret
  namespace: {{ .Values.dataScienceProjectNamespace }}
stringData:
  {{- if .Values.openaiApiKey }}
  OPENAI_API_KEY: '{{ .Values.openaiApiKey }}'
  {{- end }}
  {{- if .Values.azureOpenaiApiKey }}
  AZURE_OPENAI_API_KEY: '{{ .Values.azureOpenaiApiKey }}'
  {{- end }}
  {{- if .Values.cohereApiKey }}
  COHERE_API_KEY: '{{ .Values.cohereApiKey }}'
  {{- end }}
  {{- if .Values.graphragApiKey }}
  GRAPHRAG_API_KEY: '{{ .Values.graphragApiKey }}'
  {{- end }}
  {{- if .Values.pdfServicesClientId }}
  PDF_SERVICES_CLIENT_SECRET: '{{ .Values.pdfServicesClientSecret }}'
  {{- end }}
  {{- if .Values.milvusToken }}
  MILVUS_TOKEN: '{{ .Values.milvusToken }}'
  {{- end }}
  {{- if .Values.milvusPassword }}
  MILVUS_PASSWORD: '{{ .Values.milvusPassword }}'
  {{- end }}
  {{- if .Values.oracleUsername }}
  ORACLE_USERNAME: '{{ .Values.oracleUsername }}'
  {{- end }}
  {{- if .Values.oraclePassword }}
  ORACLE_PASSWORD: '{{ .Values.oraclePassword }}'
  {{- end }}
  {{- if .Values.oracleDsn }}
  ORACLE_DSN: '{{ .Values.oracleDsn }}'
  {{- end }}
  {{- if .Values.oracleTableName }}
  ORACLE_TABLE_NAME: '{{ .Values.oracleTableName }}'
  {{- end }}
  {{- if .Values.oracleDistanceStrategy }}
  ORACLE_DISTANCE_STRATEGY: '{{ .Values.oracleDistanceStrategy }}'
  {{- end }}
type: Opaque







