# This file is a template for the ConfigMap that contains the prompts for kotaemon.
kind: ConfigMap
apiVersion: v1
metadata:
  name: kotaemon-prompts
  namespace: {{ .Values.dataScienceProjectNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  DEFAULT_QA_TEXT_PROMPT: |
    "Use the following pieces of context to answer the question at the end in detail with clear explanation. "
    "If you don't know the answer, just say that you don't know, don't try to "
    "make up an answer. Give answer in "
    "{lang}.\n\n"
    "{context}\n"
    "Question: {question}\n"
    "Helpful Answer:"
  DEFAULT_QA_TABLE_PROMPT: |
    "Use the given context: texts, tables, and figures below to answer the question, "
    "then provide answer with clear explanation."
    "If you don't know the answer, just say that you don't know, "
    "don't try to make up an answer. Give answer in {lang}.\n\n"
    "Context:\n"
    "{context}\n"
    "Question: {question}\n"
    "Helpful Answer:"
  DEFAULT_QA_CHATBOT_PROMPT: |
    "Pick the most suitable chatbot scenarios to answer the question at the end, "
    "output the provided answer text. If you don't know the answer, "
    "just say that you don't know. Keep the answer as concise as possible. "
    "Give answer in {lang}.\n\n"
    "Context:\n"
    "{context}\n"
    "Question: {question}\n"
    "Answer:"
  DEFAULT_QA_FIGURE_PROMPT: |
    "Use the given context: texts, tables, and figures below to answer the question. "
    "If you don't know the answer, just say that you don't know. "
    "Give answer in {lang}.\n\n"
    "Context: \n"
    "{context}\n"
    "Question: {question}\n"
    "Answer: "

