# This file contains the secrets that are used by the kotaemon application
kind: Secret
apiVersion: v1
metadata:
  name: kotaemon-secrets
  namespace: {{ .Values.dataScienceProjectNamespace }}
stringData:
  OPENAI_API_KEY: '{{ .Values.openaiApiKey }}'
  AZURE_OPENAI_API_KEY: '{{ .Values.azureOpenaiApiKey }}'
  COHERE_API_KEY: '{{ .Values.cohereApiKey }}'
  GRAPHRAG_API_KEY: '{{ .Values.graphragApiKey }}'
  PDF_SERVICES_CLIENT_SECRET: '{{ .Values.pdfServicesClientSecret }}'
  MILVUS_TOKEN: '{{ .Values.milvusToken }}'
  MILVUS_PASSWORD: '{{ .Values.milvusPassword }}'
  ORACLE_USERNAME: '{{ .Values.oracleUsername }}'
  ORACLE_PASSWORD: '{{ .Values.oraclePassword }}'
  ORACLE_DSN: '{{ .Values.oracleDsn }}'
  ORACLE_TABLE_NAME: '{{ .Values.oracleTableName }}'
  ORACLE_DISTANCE_STRATEGY: '{{ .Values.oracleDistanceStrategy }}'
type: Opaque







