# This file contains the secrets that are used by the kotaemon application
kind: Secret
apiVersion: v1
metadata:
  name: kotaemon-env
  namespace: {{ .Values.dataScienceProjectNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  .env: |
    {{- if .Values.openaiApiKey }}
    APP_ENV='{{ .Values.appEnv }}'
    {{- end }}

    {{- if .Values.openaiApiKey }}
    OPENAI_API_KEY='{{ .Values.openaiApiKey }}'
    {{- end }}
    {{- if .Values.openaiApiBase }}
    OPENAI_API_BASE='{{ .Values.openaiApiBase }}'
    {{- end }}
    {{- if .Values.openaiApiVersion }}
    OPENAI_API_VERSION='{{ .Values.openaiApiVersion }}'
    {{- end }}
    {{- if .Values.openaiChatModel }}
    OPENAI_CHAT_MODEL='{{ .Values.openaiChatModel }}'
    {{- end }}
    {{- if .Values.openaiEmbeddingsModel }}
    OPENAI_EMBEDDINGS_MODEL='{{ .Values.openaiEmbeddingsModel }}'
    {{- end }}

    {{- if .Values.localOpenaiApiKey }}
    LOCAL_OPENAI_API_KEY='{{ .Values.localOpenaiApiKey }}'
    {{- end }}
    {{- if .Values.localOpenaiApiBase }}
    LOCAL_OPENAI_API_BASE='{{ .Values.localOpenaiApiBase }}'
    {{- end }}
    {{- if .Values.localOpenaiApiVersion }}
    LOCAL_OPENAI_API_VERSION='{{ .Values.localOpenaiApiVersion }}'
    {{- end }}
    {{- if .Values.localOpenaiChatModel }}
    LOCAL_OPENAI_CHAT_MODEL='{{ .Values.localOpenaiChatModel }}'
    {{- end }}
    {{- if .Values.localOpenaiApiChatPredictorName }}
    LOCAL_OPENAI_CHAT_PREDICTOR_NAME='{{ .Values.localOpenaiApiChatPredictorName }}'
    {{- end }}

    {{- if .Values.localOpenaiEmbeddingsApiBase }}
    LOCAL_OPENAI_EMBEDDINGS_API_BASE='{{ .Values.localOpenaiEmbeddingsApiBase }}'
    {{- end }}
    {{- if .Values.localOpenaiEmbeddingsApiKey }}
    LOCAL_OPENAI_EMBEDDINGS_API_KEY='{{ .Values.localOpenaiEmbeddingsApiKey }}'
    {{- end }}
    {{- if .Values.localOpenaiEmbeddingsModel }}
    LOCAL_OPENAI_EMBEDDINGS_MODEL='{{ .Values.localOpenaiEmbeddingsModel }}'
    {{- end }}
    {{- if .Values.localOpenaiApiEmbeddingsPredictorName }}
    LOCAL_OPENAI_EMBEDDINGS_PREDICTOR_NAME='{{ .Values.localOpenaiApiEmbeddingsPredictorName }}'
    {{- end }}

    {{- if .Values.azureOpenaiApiKey }}
    AZURE_OPENAI_API_KEY='{{ .Values.azureOpenaiApiKey }}'
    {{- end }}
    {{- if .Values.azureOpenaiEndpoint }}
    AZURE_OPENAI_ENDPOINT='{{ .Values.azureOpenaiEndpoint }}'
    {{- end }}
    {{- if .Values.azureOpenaiChatDeployment }}
    AZURE_OPENAI_CHAT_DEPLOYMENT='{{ .Values.azureOpenaiChatDeployment }}'
    {{- end }}
    {{- if .Values.azureOpenaiEmbeddingsDeployment }}
    AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT='{{ .Values.azureOpenaiEmbeddingsDeployment }}'
    {{- end }}

    {{- if .Values.cohereApiKey }}
    COHERE_API_KEY='{{ .Values.cohereApiKey }}'
    {{- end }}

    {{- if .Values.graphragApiKey }}
    GRAPHRAG_API_KEY='{{ .Values.graphragApiKey }}'
    {{- end }}

    {{- if .Values.pdfServicesClientId }}
    PDF_SERVICES_CLIENT_SECRET='{{ .Values.pdfServicesClientSecret }}'
    {{- end }}

    {{- if .Values.milvusHost }}
    MILVUS_HOST='{{ .Values.milvusHost }}'
    {{- end }}
    {{- if .Values.milvusPort }}
    MILVUS_PORT='{{ .Values.milvusPort }}'
    {{- end }}
    {{- if .Values.milvusCollectionsFile }}
    MILVUS_COLLECTIONS_FILE='{{ .Values.milvusCollectionsFile }}'
    {{- end }}
    {{- if .Values.milvusToken }}
    MILVUS_TOKEN='{{ .Values.milvusToken }}'
    {{- end }}
    {{- if .Values.milvusPassword }}
    MILVUS_PASSWORD='{{ .Values.milvusPassword }}'
    {{- end }}

    {{- if .Values.oracleUsername }}
    ORACLE_USERNAME='{{ .Values.oracleUsername }}'
    {{- end }}
    {{- if .Values.oraclePassword }}
    ORACLE_PASSWORD='{{ .Values.oraclePassword }}'
    {{- end }}
    {{- if .Values.oracleDsn }}
    ORACLE_DSN='{{ .Values.oracleDsn }}'
    {{- end }}
    {{- if .Values.oracleTableName }}
    ORACLE_TABLE_NAME='{{ .Values.oracleTableName }}'
    {{- end }}
    {{- if .Values.oracleDistanceStrategy }}
    ORACLE_DISTANCE_STRATEGY='{{ .Values.oracleDistanceStrategy }}'
    {{- end }}
    
    
    {{- if .Values.localModel }}
    LOCAL_MODEL='{{ .Values.localModel }}'
    {{- end }}
    {{- if .Values.localModelEmbeddings }}
    LOCAL_MODEL_EMBEDDINGS='{{ .Values.localModelEmbeddings }}'
    {{- end }}
    
    {{- if .Values.graphragLlmModel }}
    GRAPHRAG_LLM_MODEL='{{ .Values.graphragLlmModel }}'
    {{- end }}
    {{- if .Values.graphragEmbeddingModel }}
    GRAPHRAG_EMBEDDING_MODEL='{{ .Values.graphragEmbeddingModel }}'
    {{- end }}
    
    {{- if .Values.graphragEndpoint }}
    AZURE_DI_ENDPOINT='{{ .Values.azureDiEndpoint }}'
    {{- end }}
    {{- if .Values.azureDiCredential }}
    AZURE_DI_CREDENTIAL='{{ .Values.azureDiCredential }}'
    {{- end }}

    {{- if .Values.pdfServicesClientId }}
    PDF_SERVICES_CLIENT_ID='{{ .Values.pdfServicesClientId }}'
    {{- end }}
type: Opaque







