# This file contains the configuration that is used by the kotaemon application
kind: ConfigMap
apiVersion: v1
metadata:
  name: kotaemon-config
  namespace: '{{ .Values.dataScienceProjectNamespace }}'
  labels:
    app: kotaemon
    app.kubernetes.io/component: kotaemon
    app.kubernetes.io/instance: kotaemon
    app.kubernetes.io/name: kotaemon
    app.kubernetes.io/part-of: chatbots
data:
  APP_ENV: {{ .Values.appEnv }}
  OPENAI_API_BASE: {{ .Values.openaiApiBase }}
  OPENAI_CHAT_MODEL: {{ .Values.openaiChatModel }}
  OPENAI_EMBEDDINGS_MODEL: {{ .Values.openaiEmbeddingsModel }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.azureOpenaiEndpoint }}
  OPENAI_API_VERSION: {{ .Values.openaiApiVersion }}
  AZURE_OPENAI_CHAT_DEPLOYMENT: {{ .Values.azureOpenaiChatDeployment }}
  AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT: {{ .Values.azureOpenaiEmbeddingsDeployment }}
  LOCAL_MODEL: {{ .Values.localModel }}
  LOCAL_MODEL_EMBEDDINGS: {{ .Values.localModelEmbeddings }}
  GRAPHRAG_LLM_MODEL: {{ .Values.graphragLlmModel }}
  GRAPHRAG_EMBEDDING_MODEL: {{ .Values.graphragEmbeddingModel }}
  AZURE_DI_ENDPOINT: {{ .Values.azureDiEndpoint }}
  AZURE_DI_CREDENTIAL: {{ .Values.azureDiCredential }}
  PDF_SERVICES_CLIENT_ID: {{ .Values.pdfServicesClientId }}
  MILVUS_HOST: {{ .Values.milvusHost }}
  MILVUS_PORT: {{ .Values.milvusPort }}
  MILVUS_COLLECTIONS_FILE: {{ .Values.milvusCollectionsFile }}
