dataScienceProjectDisplayName: embeddings
dataScienceProjectNamespace: embeddings

createNamespace: true

model:
  root: nomic-ai
  id: nomic-embed-text-v1
  name: nomic-embed-text-v1
  displayName: Nomic AI Embed Text v1
  maxReplicas: 1
  format: pytorch
  apiProtocol: REST
  runtime:
    templateName: nomic-serving-template
    templateDisplayName: Nomic Serving Template
    resources:
      limits:
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 4Gi
  # accelerator:
  #   max: '1'
  #   min: '1'
  #   productName: NVIDIA-A10G
  connection:
    name: embeddings
  volumes:
    shm:
      sizeLimit: 2Gi
    
modelConnection:
  createSecret: true
  name: embeddings
  displayName: embeddings
  type: s3
  scheme: http
  awsAccessKeyId: minio
  awsSecretAccessKey: minio123
  awsDefaultRegion: none
  awsS3Bucket: models
  awsS3Endpoint: minio.ic-shared-minio.svc:9000

runtime:
  gpuImage: quay.io/rh-aiservices-bu/sbert-runtime:1.1.0
  cpuImage: quay.io/rh-aiservices-bu/sbert-runtime-cpu:1.1.0
  

setup:
  image: quay.io/atarazana/hf-cli:latest